[build]
  base = "."
  command = "npm install --prefix server && npm install --prefix client && npm run --prefix client build"
  publish = "client/dist"

[functions]
  directory = "server/netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200